the-gossip-project/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'team', to: 'pages#team'
  get 'contact', to: 'pages#contact'
  get 'potins/:id', to: 'pages#show', as: 'potins_id'
  get 'welcome/:first_name', to: 'pages#welcome'
  get 'potins/:id/user', to: 'pages#show_user', as: 'user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

the-gossip-project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

the-gossip-project/app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

the-gossip-project/app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :tag_gossips, dependent: :destroy
	has_many :tags, through: :tag_gossips
end

the-gossip-project/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :receiver, class_name: "User"
end

the-gossip-project/app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tag_gossips, dependent: :destroy
	has_many :gossips, through: :tag_gossips
end

the-gossip-project/app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
	belongs_to :gossip 
	belongs_to :tag
end

the-gossip-project/app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: 'receiver_id', class_name: "PrivateMessage"
end

the-gossip-project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

the-gossip-project/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def team; end

  def contact; end

  def welcome
  	@user = params[:first_name]
  end

  def home
  	@potins = Gossip.all
  end

  def show
  	@self = Gossip.find(params[:id])
  end

  def show_user
  	@self_potin = Gossip.find(params[:id])
  	@self = @self_potin.user
  end
end

the-gossip-project/app/helpers/application_helper.rb
module ApplicationHelper
end

the-gossip-project/app/helpers/pages_helper.rb
module PagesHelper
end

the-gossip-project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">The Gossip Project</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Home", root_path %><span style="margin-left: 20px;"></span>
      </li>
      <li class="nav-item">
        <%= link_to "Team", team_path %><span style="margin-left: 20px;"></span>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", contact_path %>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

the-gossip-project/app/views/pages/contact.html.erb
<div class="container my-3">
	<h1>Nous contacter</h1>

	<p>Tu peux nous contacter via email :</p>
	<ul>
		<li>billel.ketrouci@gmail.com</li>
		<li>dien.kika@gmail.com</li>
	</ul>
</div>

the-gossip-project/app/views/pages/home.html.erb
<div class="container my-3">
	<h1>Bienvenido, el amigo</h1>
	<h4>Voici notre liste de potins : </h4>
	<ul>
	<div class="row d-flex justify-content-start">
	<% @potins.each do |potin| %>
	<div class="col-md-6 col-lg-4">
		<div class="card" style="width: 18rem;">
  			<div class="card-body">
    			<h5 class="card-title"><%= potin.title %></h5>
   				<h6 class="card-subtitle mb-2 text-muted">Id n°<%= potin.id %></h6>
    			<p class="card-text"><%= potin.content %></p>
    			<%= link_to "Voir le potin", potins_id_path(potin.id) %>
  			</div>
		</div>
	</div>
	<% end %></div>
	</ul>
</div>

the-gossip-project/app/views/pages/show.html.erb
<div class="container my-3">
	<h1>Voici le potin n°<%= @self.id %>: </h1>
	<ul>
		<li><%= @self.title %></li>
		<li><%= @self.content %></li>
	</ul>
	<%= link_to "Voir l'utilisateur qui à posté ce potin", user_path(@self.id) %>
</div>

the-gossip-project/app/views/pages/show_user.html.erb
<div class="container my-3">
	<ul>
		<li><%= @self.first_name %> <%= @self.last_name %></li>
		<li>Description : <%= @self.description %></li>
		<li><%= @self.email %></li>
		<li><%= @self.age %> ans</li>
	</ul>
</div>

the-gossip-project/app/views/pages/team.html.erb
<div class="container my-3">
	<h1>Ma team</h1>

	<p>billel Ketrouci</p>
	<p>kika Dien</p>
	<p>Le reste c'est des fragiles qui ont abandonnés ...</p>
</div>

the-gossip-project/app/views/pages/welcome.html.erb
<div class="container my-3">
	<h1>Bienvenue, <%= @user %></h1>
	<p>Ici c'est notre super site de potins, il est chouette, non ?</p>
</div>